language: php

php:
  - 7.2

addons:
  chrome: stable

branches:
  - master

install:
  - composer install --prefer-dist --no-interaction
  - cp .env.example .env
  - php artisan key:generate

cache:
  directories:
    - vendor/

after_success:
  - echo "Success!"